### ISSUE TITLE
impossible d'ajouter la source de aidoku

### ISSUE THREAD

**Issue by ydrysse** [Moomooo95/aidoku-french-sources#1]
Bonsoir,

 je me permet de vous écrire ce message car je n'arrive à ajouter votre source dans l'application aidoku.
merci par avance pour la réponse.

**Comment by Moomooo95** [comment]
Bonsoir,

Voici le lien à mettre lors de l'ajout d'une source sur aidoku : https://raw.githubusercontent.com/Moomooo95/aidoku-french-sources/gh-pages/
