### ISSUE TITLE
Liens obsolètes

### ISSUE THREAD

**Issue by Hidax517** [Moomooo95/aidoku-french-sources#2]
Bonjour, c'est pour dire que la plupart des sites présents dans la source sont obsolètes et ne fonctionnent plus. De plus, serait-il possible d'ajouter un site comme Sushi-Scan, par exemple, car il ne fonctionne quasiment jamais sur la source inclus dans Aidoku et il contient presque tous les mangas?

Btw, merci pour les travaux, c'est grâce à vous que j'ai pu lire en français sur Aidoku ainsi que sur Paperback 🙏

**Comment by Moomooo95** [comment]
Les sources ont été mises à jour. 
De nouvelles sources ont été ajoutées (PhenixScans, SushiScans, Manga Scan, LelScanFR)
Tous fonctionnent sauf manga-scantrad pour le moment.
