### ISSUE TITLE
les sources ne fonctionne plus 

### ISSUE THREAD

**Issue by wakuro** [Moomooo95/aidoku-french-sources#3]
Bonjour, déjà merci pour le taff que vous avez fourni grâce à vous je peux lire sur le ipad sans passer par un site web mal optimisé et bourré de pub. Malheureusement depuis quelque temps les différentes sources ne fonctionnent plus comme notamment manga scantrad, reaper scan etc. de mon côté seulement astral manga fonctionne mais il y a rien à lire dessus. ce que j'aurai aimé savoir si il serai de remédier au problème merci par avance et bonne journée à vous.

**Comment by Moomooo95** [comment]
Les sources ont été mise à jour.
Tous fonctionne sauf manga-scantrad pour le moment.
