### ISSUE TITLE
LelScan nombre de chapitres

### ISSUE THREAD

**Issue by Aituglo** [Moomooo95/aidoku-french-sources#4]
Hello, déjà merci beaucoup pour ce travail, c'est top !

Je tenais juste à te dire que pour lelscan, seulement les 100 derniers chapitres sont pris, c'est probablement dû au fait qu'il y ait plusieurs pages sur le site quand il y a plus de 100 chapitres.

À voir si il est tout de même possible de parser les autres chapitres au delà des 100 derniers.

Merci beaucoup

**Comment by Moomooo95** [comment]
Salut,
Je viens de régler le problème. Tu as juste à mettre à jour la source sur Aidoku.
Le chargement des chapitres peut être un peu long en fonction du nombre de pages puisqu'elles sont toutes parcourues pour récupérer tous les chapitres.
