### ISSUE TITLE
Problèmes sur différentes sources 

### ISSUE THREAD

**Issue by CptBigBen** [Moomooo95/aidoku-french-sources#5]
Hello,

tout d’abord merci énormément pour ton travail.
Je voulais juste te signaler que plusieurs sources fr ne fonctionnent plus comme manga scantrad et les sushi scan.

merci d’avance pour ton temps !

**Comment by Moomooo95** [comment]
Salut,
Je viens de régler le problème sur la source mangascantrad.
Par contre, les sources phenixscans, sushiscans et sushiscan ont l'air de fonctionner de temps en temps, donc je pense, c'est un problème avec cloudflare et ça, c'est un problème du côté d'Aidoku.
